### ISSUE TITLE
Saving settings causes duplicated combatLogParsers

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#230]
Run classic 2v2 test. Works fine.

Then open settings, make no changes and click save.

Then run test again. Now fails.

This sort of thing in logs. Suspect we're duplicating the log listener. 

```
[2022-11-13 16:56:07.698] [info]  [CombatLogParser] Locking path 'D:\World of Warcraft\_classic_\Logs' for exclusive event processing.
[2022-11-13 16:56:07.699] [info]  [ClassicLogHandler] Handling ZONE_CHANGE line: {
  original: `10/16 12:44:44.182  ZONE_CHANGE,562,"Blade's Edge Arena",0`,
  _linePosition: 32,
  _lineLength: 58,
  _args: [ 'ZONE_CHANGE' ],
  _argsListLen: 1,
  timestamp: '10/16 12:44:44.182'
}
[2022-11-13 16:56:07.699] [info]  [ClassicLogHandler] Zone change into Arena
[2022-11-13 16:56:07.699] [debug] [ClassicLogHandler] Starting arena at date: 2022-10-16T11:44:44.182Z
[2022-11-13 16:56:07.700] [info]  [LogHandler] Good to record: 2v2
[2022-11-13 16:56:07.700] [info]  [Logutils] Start recording a video for category: 2v2
[2022-11-13 16:56:07.701] [info]  [Recorder] Start recording by cancelling buffer restart
[2022-11-13 16:56:07.701] [info]  [Recorder] Buffer restart interval cleared
[2022-11-13 16:56:07.703] [info]  [CombatLogParser] Locking path 'D:\World of Warcraft\_classic_\Logs' for exclusive event processing.
[2022-11-13 16:56:07.703] [info]  [ClassicLogHandler] Handling ZONE_CHANGE line: {
  original: `10/16 12:44:44.182  ZONE_CHANGE,562,"Blade's Edge Arena",0`,
  _linePosition: 32,
  _lineLength: 58,
  _args: [ 'ZONE_CHANGE' ],
  _argsListLen: 1,
  timestamp: '10/16 12:44:44.182'
}
[2022-11-13 16:56:07.703] [info]  [ClassicLogHandler] Zone change into Arena
[2022-11-13 16:56:07.704] [debug] [ClassicLogHandler] Starting arena at date: 2022-10-16T11:44:44.182Z
[2022-11-13 16:56:07.704] [info]  [LogHandler] Good to record: 2v2
[2022-11-13 16:56:07.704] [error] [LogHandler] Avoiding error by not attempting to start recording true false
[2022-11-13 16:56:07.710] [error] [LogHandler] Tried to set timestamp to -21.774999856948853
[2022-11-13 16:56:07.712] [error] [LogHandler] Tried to set timestamp to -21.774999856948853
[2022-11-13 16:56:07.714] [info]  [ClassicLogHandler] No enemy players left so ending game.
[2022-11-13 16:56:07.715] [debug] [ClassicLogHandler] Stopping arena at date: 2022-10-16T11:44:54.182Z
[2022-11-13 16:56:07.715] [info]  [ClassicLogHandler] Number of combatants found:  4
[2022-11-13 16:56:07.715] [info]  [ClassicLogHandler] Logging combatants
[2022-11-13 16:56:07.716] [info]  {
  _GUID: 'Player-4811-036B0F06',
  _name: 'Alexpals',
  _realm: 'Giantstalker',
  _teamID: 1,
  _specID: 65
} Player-4811-036B0F06
[2022-11-13 16:56:07.716] [info]  {
  _GUID: 'Player-4811-0381F1C0',
  _name: 'Sperge',
  _realm: 'Giantstalker',
  _teamID: 1,
  _specID: 71
} Player-4811-0381F1C0
[2022-11-13 16:56:07.717] [info]  {
  _GUID: 'Player-4476-043F3626',
  _name: 'Jungledck',
  _realm: 'Gehennas',
  _teamID: 0,
  _specID: 262
} Player-4476-043F3626
[2022-11-13 16:56:07.717] [info]  {
  _GUID: 'Player-4476-045C7252',
  _name: 'Notyourlock',
  _realm: 'Gehennas',
  _teamID: 0,
  _specID: 267
} Player-4476-045C7252
[2022-11-13 16:56:07.717] [info]  [ClassicLogHandler] Friendly deaths:  0
[2022-11-13 16:56:07.717] [info]  [ClassicLogHandler] Enemy deaths:  2
[2022-11-13 16:56:07.718] [info]  [Logutils] Stop recording video for category: 2v2
[2022-11-13 16:56:07.718] [info]  [Recorder] Stop recording after overrun
[2022-11-13 16:56:07.718] [info]  [Recorder] Overrun: 3
[2022-11-13 16:56:07.719] [info]  [ClassicLogHandler] No enemy players left so ending game.
[2022-11-13 16:56:07.720] [debug] [ClassicLogHandler] Stopping arena at date: 2022-10-16T11:44:54.182Z
[2022-11-13 16:56:07.720] [info]  [ClassicLogHandler] Number of combatants found:  4
[2022-11-13 16:56:07.720] [info]  [ClassicLogHandler] Logging combatants
[2022-11-13 16:56:07.720] [info]  {
  _GUID: 'Player-4811-036B0F06',
  _name: 'Alexpals',
  _realm: 'Giantstalker',
  _teamID: 1,
  _specID: 65
} Player-4811-036B0F06
[2022-11-13 16:56:07.721] [info]  {
  _GUID: 'Player-4811-0381F1C0',
  _name: 'Sperge',
  _realm: 'Giantstalker',
  _teamID: 1,
  _specID: 71
} Player-4811-0381F1C0
[2022-11-13 16:56:07.721] [info]  {
  _GUID: 'Player-4476-043F3626',
  _name: 'Jungledck',
  _realm: 'Gehennas',
  _teamID: 0,
  _specID: 262
} Player-4476-043F3626
[2022-11-13 16:56:07.721] [info]  {
  _GUID: 'Player-4476-045C7252',
  _name: 'Notyourlock',
  _realm: 'Gehennas',
  _teamID: 0,
  _specID: 267
} Player-4476-045C7252
[2022-11-13 16:56:07.721] [info]  [ClassicLogHandler] Friendly deaths:  0
[2022-11-13 16:56:07.722] [info]  [ClassicLogHandler] Enemy deaths:  2
[2022-11-13 16:56:07.722] [info]  [Logutils] Stop recording video for category: 2v2
[2022-11-13 16:56:07.722] [info]  [Recorder] Stop recording after overrun
[2022-11-13 16:56:07.722] [info]  [Recorder] Overrun: 3
[2022-11-13 16:56:10.728] [info]  [OBS] obsRecorder: stop
[2022-11-13 16:56:10.729] [info]  [OBS] obsRecorder: stop
[2022-11-13 16:56:10.759] [debug] [OBS] Asserted OBS signal: stopping
[2022-11-13 16:56:10.990] [error] [OBS] [object Object]
[2022-11-13 16:56:10.990] [error] [OBS] OBS signal value unexpected stop stopping
[2022-11-13 16:56:10.991] [error] UnhandledPromiseRejectionWarning: Error: OBS behaved unexpectedly (3)
    at x (C:\Users\alexa\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:420028)
    at Object.t.stop (C:\Users\alexa\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:418406)
    at Timeout._onTimeout (C:\Users\alexa\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:422613)
[2022-11-13 16:57:01.489] [error] [OBS] [object Object]
[2022-11-13 16:57:01.489] [error] [OBS] OBS signal value unexpected wrote stop
[2022-11-13 16:57:01.490] [error] UnhandledPromiseRejectionWarning: Error: OBS behaved unexpectedly (3)
    at x (C:\Users\alexa\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:420028)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at Object.t.stop (C:\Users\alexa\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:418426)
    at Timeout._onTimeout (C:\Users\alexa\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:422613)
[2022-11-13 16:57:02.651] [info]  [ClassicLogHandler] Handling ZONE_CHANGE line: {
  original: '10/16 12:44:54.182  ZONE_CHANGE,571,"Dalaran",0',
  _linePosition: 32,
  _lineLength: 47,
  _args: [ 'ZONE_CHANGE' ],
  _argsListLen: 1,
  timestamp: '10/16 12:44:54.182'
}
[2022-11-13 16:57:02.651] [info]  [ClassicLogHandler] Uninteresting zone change
[2022-11-13 16:57:02.652] [info]  [ClassicLogHandler] Handling ZONE_CHANGE line: {
  original: '10/16 12:44:54.182  ZONE_CHANGE,571,"Dalaran",0',
  _linePosition: 32,
  _lineLength: 47,
  _args: [ 'ZONE_CHANGE' ],
  _argsListLen: 1,
  timestamp: '10/16 12:44:54.182'
}
[2022-11-13 16:57:02.653] [info]  [ClassicLogHandler] Uninteresting zone change
```

**Comment by aza547** [comment]
Fixed on main.
