### ISSUE TITLE
After Updating to 3.3.1: Exception height of g.obsResolution is undefined

### ISSUE THREAD

**Issue by mmgucci** [aza547/wow-recorder#269]
After updating to 3.3.1 I get a Javascript exception when opening Warcraft Recorder or saving the settings.

Not sure if I did the update correctly as I just installed the latest version over the existing one.
I had to reconfigure the recording path and log path.

After startup
![image](https://user-images.githubusercontent.com/8050921/210309462-1f1b3ad1-ab0a-4443-b849-13216b3dc94d.png)

After saving settings
TypeError: Cannot destructure property 'height' of 'g.obsResolutions[this.resolution]' as it is undefined.
    at v.configureOBS (C:\Users\marku\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:371532)
    at v.configure (C:\Users\marku\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:370425)
    at BrowserWindow.<anonymous> (C:\Users\marku\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:406749)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Thanks for you work aza547 :heart:

**Comment by aza547** [comment]
This was a but in the 3.3.0 config that I missed, if you upgraded from 3.3.0 to 3.3.1 this will happen.

Workaround is to delete the config and restart the app - specifically the file
`C:\Users\**USERNAME**\AppData\Roaming\WarcraftRecorder\config-v3.json`

Please re-open if that doesn't resolve it for you :)
