### ISSUE TITLE
App freezes but keeps recording

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#460]
Raiding tonight and after a few hours my app froze. Think I had the app open for 3-4 days solid.

This in logs:

```
[2023-12-20 22:23:56.975] [error] Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter.s.send (node:electron/js2c/browser_init:2:86507)
    at EventEmitter._.send (node:electron/js2c/browser_init:2:72283)
    at t.updateRecStatus (C:\Users\Alex\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:509331)
    at w.refreshStatus (C:\Users\Alex\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:439307)
    at S.<anonymous> (C:\Users\Alex\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:437318)
    at S.emit (node:events:513:28)
    at S.handleSignal (C:\Users\Alex\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:458325)
    at obsRecordingFactory.signalHandler (C:\Users\Alex\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:448422)
[2023-12-20 22:23:56.975] [error] Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at EventEmitter.s.send (node:electron/js2c/browser_init:2:86507)
    at EventEmitter._.send (node:electron/js2c/browser_init:2:72283)
    at t.updateMicStatus (C:\Users\Alex\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:509400)
    at w.refreshStatus (C:\Users\Alex\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:439595)
    at S.<anonymous> (C:\Users\Alex\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:437318)
    at S.emit (node:events:513:28)
    at S.handleSignal (C:\Users\Alex\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:458325)
    at obsRecordingFactory.signalHandler (C:\Users\Alex\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:448422)
```

**Comment by aza547** [comment]
Restarting app resolved it. But weird none-the-less.

**Comment by aza547** [comment]
[WarcraftRecorder-2023-12-17.log](https://github.com/aza547/wow-recorder/files/13733346/WarcraftRecorder-2023-12-17.log)

**Comment by aza547** [comment]
Not seen this since so closing
