### ISSUE TITLE
Large video fails to upload

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#489]
```
[2024-04-26 01:25:14.372] [error] [CloudClient] File upload failed 2024-04-25 23-44-30 - Meraned - Uldaman Legacy of Tyr +10 (+0).mp4 400 <?xml version="1.0" encoding="UTF-8"?><Error><Code>EntityTooLarge</Code><Message>Your proposed upload exceeds the maximum allowed object size.</Message></Error>
[2024-04-26 01:25:14.373] [error] [VideoProcessQueue] Error processing video: Error: Uploading a file to the cloud failed Error: Uploading a file to the cloud failed
    at d.putFile (C:\Users\tjvho\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:593076)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at h.processUploadQueueItem (C:\Users\tjvho\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:507192)
```

Seems that we're not doing multi-part upload here. 

The object size limit is still way bigger: https://developers.cloudflare.com/r2/reference/limits/

**Comment by aza547** [comment]
[WarcraftRecorder-2024-04-25.log](https://github.com/aza547/wow-recorder/files/15126358/WarcraftRecorder-2024-04-25.log)
