### ISSUE TITLE
Uploads fail on 6.3.0

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#572]
```
[2024-12-19 09:30:40.098] [info]  [VideoProcessQueue] Now uploading video D:\warcraft-recorder-files\2024-12-18 19-03-37 - Alextides - Queen Ansurek [M] (Wipe).mp4
[2024-12-19 09:30:40.099] [info]  [CloudClient] Uploading D:\warcraft-recorder-files\2024-12-18 19-03-37 - Alextides - Queen Ansurek [M] (Wipe).mp4 to 2024-12-18 19-03-37 - Alextides - Queen Ansurek [M] (Wipe).mp4 with rate limit 100
[2024-12-19 09:30:40.100] [info]  [CloudClient] Create signed multipart upload 2024-12-18 19-03-37 - Alextides - Queen Ansurek [M] (Wipe).mp4 1231996312
[2024-12-19 09:30:40.368] [debug] [CloudClient] Multipart upload has 12 parts
[2024-12-19 09:30:40.368] [debug] [CloudClient] Starting part 1
[2024-12-19 09:30:53.867] [debug] [CloudClient] Finished part 1 etag 5fd419e798a89a96e1c313a1573afc64
[2024-12-19 09:30:53.867] [debug] [CloudClient] Starting part 2
[2024-12-19 09:30:53.874] [warn]  [CloudClient] Multipart retryable failure: 2024-12-18 19-03-37 - Alextides - Queen Ansurek [M] (Wipe).mp4 Request failed with status code 400
[2024-12-19 09:31:07.347] [debug] [CloudClient] Finished part 2 etag 457050d934fb56a1aaf2af87ec959cb8
[2024-12-19 09:31:07.348] [debug] [CloudClient] Starting part 3
[2024-12-19 09:31:20.892] [debug] [CloudClient] Finished part 3 etag f8a46d43453dbd2ba166d547441b4082
[2024-12-19 09:31:20.892] [debug] [CloudClient] Starting part 4
[2024-12-19 09:31:20.895] [warn]  [CloudClient] Multipart retryable failure: 2024-12-18 19-03-37 - Alextides - Queen Ansurek [M] (Wipe).mp4 Request failed with status code 400
[2024-12-19 09:31:34.356] [debug] [CloudClient] Finished part 4 etag b4a25fd55a883bef44243c2c13008435
[2024-12-19 09:31:34.356] [debug] [CloudClient] Starting part 5
[2024-12-19 09:31:34.359] [warn]  [CloudClient] Multipart retryable failure: 2024-12-18 19-03-37 - Alextides - Queen Ansurek [M] (Wipe).mp4 Request failed with status code 400
[2024-12-19 09:31:47.704] [debug] [CloudClient] Finished part 5 etag 7c56e8ab9bb8694eacbedfa785856ccb
[2024-12-19 09:31:47.704] [debug] [CloudClient] Starting part 6
[2024-12-19 09:32:00.823] [warn]  [CloudClient] Multipart retryable failure: 2024-12-18 19-03-37 - Alextides - Queen Ansurek [M] (Wipe).mp4 Request failed with status code 503
[2024-12-19 09:32:14.233] [warn]  [CloudClient] Multipart retryable failure: 2024-12-18 19-03-37 - Alextides - Queen Ansurek [M] (Wipe).mp4 Request failed with status code 503
[2024-12-19 09:32:27.531] [warn]  [CloudClient] Multipart retryable failure: 2024-12-18 19-03-37 - Alextides - Queen Ansurek [M] (Wipe).mp4 Request failed with status code 503
[2024-12-19 09:32:40.920] [warn]  [CloudClient] Multipart retryable failure: 2024-12-18 19-03-37 - Alextides - Queen Ansurek [M] (Wipe).mp4 Request failed with status code 503
[2024-12-19 09:32:54.042] [warn]  [CloudClient] Multipart retryable failure: 2024-12-18 19-03-37 - Alextides - Queen Ansurek [M] (Wipe).mp4 Request failed with status code 503
[2024-12-19 09:32:54.042] [error] [CloudClient] Multipart upload failed: 2024-12-18 19-03-37 - Alextides - Queen Ansurek [M] (Wipe).mp4
[2024-12-19 09:32:54.043] [error] [VideoProcessQueue] Error processing video: Error: Multipart upload failed, retry attempts exhausted Error: Multipart upload failed, retry attempts exhausted
    at CloudClient.doMultiPartUpload (D:\checkouts\warcraft-recorder\.erb\dll\main.bundle.dev.js:74631:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async CloudClient.putFile (D:\checkouts\warcraft-recorder\.erb\dll\main.bundle.dev.js:74317:13)
    at async VideoProcessQueue.processUploadQueueItem (D:\checkouts\warcraft-recorder\.erb\dll\main.bundle.dev.js:69121:13)
```

**Comment by aza547** [comment]
Seems to be as a result of the new electron version. Downgrading the electron version resolves it. 

Not convinced we're actually getting these responses from R2. It's all HTTPS so hard to tell. At least it's the client that's responsible.
