### ISSUE TITLE
Recording sound but no video

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#61]
> 1. What is happening? Sound recorded but no display
> 2. What are you expecting to happen? both sound and display
>  3. What icon is showing in the bottom left of the application?  Sleep then ready and waiting then recording then saving
> 4. What version are you running? 2.5.0

[2022-08-29_14-46-49 (3).txt](https://github.com/aza547/wow-recorder/files/9456104/2022-08-29_14-46-49.3.txt)

```
[2022-08-29 15:06:56.021] [info]  Wow.exe has started
[2022-08-29 15:06:56.022] [info]  Recorder: Start recording buffer
[2022-08-29 15:06:56.022] [debug] OBS is now recording...
[2022-08-29 15:06:56.022] [debug] Started?
[2022-08-29 15:06:56.118] [debug] Started signalInfo.type: recording (expected: "recording")
[2022-08-29 15:06:56.120] [debug] Started signalInfo.signal: start (expected: "start")
[2022-08-29 15:06:56.120] [debug] Started!
[2022-08-29 15:11:56.026] [info]  Recorder: Restart recording buffer
[2022-08-29 15:11:56.027] [debug] OBS stopping recording...
[2022-08-29 15:11:56.058] [debug] On stop signalInfo.type: recording (expected: "recording")
[2022-08-29 15:11:56.059] [debug] On stop signalInfo.signal: stopping (expected: "stopping")
[2022-08-29 15:11:56.242] [debug] After stop signalInfo.type: recording (expected: "recording")
[2022-08-29 15:11:56.242] [debug] After stop signalInfo.signal: stop (expected: "stop")
[2022-08-29 15:11:56.244] [debug] Stopped!
[2022-08-29 15:11:58.041] [info]  Deleting: C:/Users/tanti/AppData/Local/Temp/WarcraftRecorder/2022-08-29 14-52-26.mp4
[2022-08-29 15:11:58.044] [debug] OBS is now recording...
[2022-08-29 15:11:58.044] [debug] Started?
[2022-08-29 15:11:58.129] [debug] Started signalInfo.type: recording (expected: "recording")
[2022-08-29 15:11:58.129] [debug] Started signalInfo.signal: start (expected: "start")
[2022-08-29 15:11:58.130] [debug] Started!
[2022-08-29 15:12:13.041] [info]  Handling zone change:  8/29 15:12:06.285  ZONE_CHANGE,1803,"Dalaran",0
[2022-08-29 15:12:13.042] [info]  ZONE_CHANGE into BG, start recording
[2022-08-29 15:12:13.042] [info]  Recorder: Start recording
[2022-08-29 15:12:13.042] [info]  Handling zone change:  8/29 15:12:06.570  ZONE_CHANGE,1803,"Seething Shore",0
[2022-08-29 15:18:35.869] [info]  Handling zone change:  8/29 15:17:46.846  ZONE_CHANGE,1220,"Dalaran",0
[2022-08-29 15:18:35.870] [info]  ZONE_CHANGE out of BG, stop recording
[2022-08-29 15:18:35.870] [info]  Recorder: Stop recording after 0 seconds
[2022-08-29 15:18:35.871] [info]  Recorder: {"name":"Seething Shore","category":"Battlegrounds","zoneID":1803,"duration":341,"result":false}
[2022-08-29 15:18:35.887] [debug] OBS stopping recording...
[2022-08-29 15:18:35.919] [debug] On stop signalInfo.type: recording (expected: "recording")
[2022-08-29 15:18:35.920] [debug] On stop signalInfo.signal: stopping (expected: "stopping")
[2022-08-29 15:18:36.107] [debug] After stop signalInfo.type: recording (expected: "recording")
[2022-08-29 15:18:36.108] [debug] After stop signalInfo.signal: stop (expected: "stop")
[2022-08-29 15:18:36.108] [debug] Stopped!
[2022-08-29 15:18:38.467] [info]  Ready to cut video.
[2022-08-29 15:18:38.468] [info]  Initial duration: 397.75 Desired duration: 341 Calculated start time: 57
[2022-08-29 15:18:42.158] [info]  Wow.exe has stopped
[2022-08-29 15:18:42.158] [info]  Recorder: Stop recording buffer
[2022-08-29 15:18:42.158] [debug] OBS stopping recording...
[2022-08-29 15:18:44.162] [info]  Deleting: C:/Users/tanti/AppData/Local/Temp/WarcraftRecorder/2022-08-29 15-06-56.mp4
[2022-08-29 15:18:44.471] [info]  FFmpeg cut video succeeded
[2022-08-29 15:18:44.473] [error] (node:17380) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'name')
    at O (C:\Users\tanti\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:492993)
    at t.writeMetadataFile (C:\Users\tanti\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:492431)
    at Timeout._onTimeout (C:\Users\tanti\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:489238)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-08-29 15:18:44.473] [error] (node:17380) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either
```

```
[2022-08-29 15:31:07.227] [info]  App starting
[2022-08-29 15:31:07.293] [info]  App ready
[2022-08-29 15:31:07.336] [debug] Initializing OBS...
[2022-08-29 15:31:11.505] [debug] OBS initialized
[2022-08-29 15:31:11.505] [debug] Configuring OBS
[2022-08-29 15:31:11.513] [debug] Available encoder: ["none","obs_x264","obs_qsv11","ffmpeg_nvenc","jim_nvenc"]
[2022-08-29 15:31:11.513] [debug] Selected encoder: jim_nvenc
[2022-08-29 15:31:11.641] [debug] OBS Configured
[2022-08-29 15:31:17.087] [info]  User opened settings
[2022-08-29 15:31:17.253] [info]  Got from config store:  storage-path D:\
[2022-08-29 15:31:17.256] [info]  Got from config store:  log-path C:\Program Files (x86)\World of Warcraft\_retail_\Logs
[2022-08-29 15:31:17.258] [info]  Got from config store:  max-storage 200
[2022-08-29 15:31:17.259] [info]  Got from config store:  start-up true
[2022-08-29 15:31:33.100] [info]  OS level set start-up behaviour:  true
[2022-08-29 15:31:33.101] [info]  Setting in config store:  start-up true
[2022-08-29 15:31:33.104] [info]  User closed settings
[2022-08-29 15:32:17.448] [info]  Wow.exe has started
[2022-08-29 15:32:17.449] [info]  Recorder: Start recording buffer
[2022-08-29 15:32:17.449] [debug] OBS is now recording...
[2022-08-29 15:32:17.449] [debug] Started?
[2022-08-29 15:32:17.539] [debug] Started signalInfo.type: recording (expected: "recording")
[2022-08-29 15:32:17.540] [debug] Started signalInfo.signal: start (expected: "start")
[2022-08-29 15:32:17.540] [debug] Started!
```

**Comment by aza547** [comment]
[2022-08-29_21-10-11.txt](https://github.com/aza547/wow-recorder/files/9456117/2022-08-29_21-10-11.txt)
[2022-08-29_14-46-49 (4).txt](https://github.com/aza547/wow-recorder/files/9456118/2022-08-29_14-46-49.4.txt)

**Comment by aza547** [comment]
Think someone else saw this on reddit too.

**Comment by aza547** [comment]
Another report of this (Chrisadan). 

> 1. Video is not showing, audio is working
> 2. video to show
> 3. Sleeping dude
> 4. was running version 2.5.0

[2022-09-01_13-01-09.txt](https://github.com/aza547/wow-recorder/files/9472299/2022-09-01_13-01-09.txt)
[WarcraftRecorder-2022-09-01.log](https://github.com/aza547/wow-recorder/files/9472300/WarcraftRecorder-2022-09-01.log)

**Comment by aza547** [comment]
Need to confirm if this still happens in 2.6.0. Might have been fixed by OBS/OSN upgrade.

**Comment by aza547** [comment]
Seems this is fixed for at least 1 person and I haven't heard it's still broken from anyone yet. Closing this, can reopen if we get further reports.
