### ISSUE TITLE
Various PVE problems 

### ISSUE THREAD

**Issue by aza547** [aza547/wow-recorder#98]
Reported by Tmb. 

> ok i'll just write it here then
first i've set a storage maximum of 100GB but the folder is already 123 GB big
then out of my arena games yesterday some are missing and out of my whole raid yesterday there is only one jailer try out of the whole evening
the record icon is also showing all the time even now when the game isn't even running
i have the 2.6.1 version
want me to send you the logs in discord?

OK - sounds like 2 issues. Yeah please - logs are great. Thanks for the details!
Any chance the Jailer try was the first one?
of the night
> oh and sometimes it records single m+ bosses and heroic bosses even tho i turned logging off for heroic and m+ in the addon you suggested
no we did him last

**Comment by aza547** [comment]
[logs-20220913T193814Z-001.zip](https://github.com/aza547/wow-recorder/files/9560272/logs-20220913T193814Z-001.zip)

**Comment by aza547** [comment]
Bug in 

```
/**
 * isVideoProtected
 */
 const isVideoProtected = (videoPath: string) => {
    const metadataPath = getMetadataFileForVideo(videoPath);
    const metadataJSON = fs.readFileSync(metadataPath);
    const metadata = JSON.parse(metadataJSON);
    return Boolean(metadata.protected);
}  
```

We should first check that the metadata file exists before trying to read it. It falls over if the JSON doesn't exist and leaves the app in a bad state. 

```
[2022-09-13 19:10:10.710] [debug] Running size monitor
[2022-09-13 19:10:11.106] [error] (node:20820) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'E:/wow recorder/2022-08-17 21-32-51.json'
    at Object.openSync (node:fs:585:3)
    at Object.func [as openSync] (node:electron/js2c/asar_bundle:5:1812)
    at Object.readFileSync (node:fs:453:35)
    at Object.e.readFileSync (node:electron/js2c/asar_bundle:5:9160)
    at C (C:\Users\moritz\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:377685)
    at O (C:\Users\moritz\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:377424)
    at k (C:\Users\moritz\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:377259)
    at Timeout._onTimeout (C:\Users\moritz\AppData\Local\Programs\WarcraftRecorder\resources\app.asar\dist\main\main.js:14:373014)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
(Use `WarcraftRecorder --trace-warnings ...` to show where the warning was created)
[2022-09-13 19:10:11.107] [error] (node:20820) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by tdaugaard** [comment]
> @tdaugaard could you include a fix for this in your size monitor changes (or confirm that it's already there?)

Yes! WIll do shortly.

Do you want me to make a guard for accidental logging of M+ bosses as well until the M+ feature is done?

**Comment by aza547** [comment]
> > @tdaugaard could you include a fix for this in your size monitor changes (or confirm that it's already there?)
> 
> Yes! WIll do shortly.
> 
> Do you want me to make a guard for accidental logging of M+ bosses as well until the M+ feature is done?

Ah I wouldn't worry about that - unless you think it's cheap to do?

**Comment by tdaugaard** [comment]
> Ah I wouldn't worry about that - unless you think it's cheap to do?

It will be - just a flag to tell if a challenge mode dungeon is started and then skip encounter record. I'll fix it! =)

**Comment by aza547** [comment]
Fixed on main. Closing. Will be out in next release.
